[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = ["-C", "link-arg=-Tlinker/x86_64.ld"]

[target.aarch64-unknown-none]
rustflags = ["-C", "link-arg=-Tlinker/aarch64.ld"]

[target.riscv64gc-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tlinker/riscv64.ld"]

[target.loongarch64-unkown-none]
rustflags = ["-C","link-arg=-Tlinker/loongarch64.ld"]